Fixed. "bundle" from bundler conflicts
```
Step 9 : RUN eval "$(rbenv init -)"; rbenv install 2.4.3 &&  eval "$(rbenv init -)"; rbenv global 2.4.3 &&  eval "$(rbenv init -)"; gem update --system &&  eval "$(rbenv init -)"; gem install bundler
 ---> Running in c8f7f9dbaeaa
Downloading ruby-2.4.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.3.tar.bz2
Installing ruby-2.4.3...
Installed ruby-2.4.3 to /usr/local/rbenv/versions/2.4.3

Updating rubygems-update
Successfully installed rubygems-update-2.7.3
Parsing documentation for rubygems-update-2.7.3
Installing ri documentation for rubygems-update-2.7.3
Installing darkfish documentation for rubygems-update-2.7.3
Done installing documentation for rubygems-update after 43 seconds
Parsing documentation for rubygems-update-2.7.3
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.3
Bundler 1.16.0 installed
RubyGems 2.7.3 installed
Regenerating binstubs
RubyGems system software updated
ERROR:  Error installing bundler:
  "bundle" from bundler conflicts with /usr/local/rbenv/versions/2.4.3/bin/bundle
The command '/bin/sh -c eval "$(rbenv init -)"; rbenv install 2.4.3 &&  eval "$(rbenv init -)"; rbenv global 2.4.3 &&  eval "$(rbenv init -)"; gem update --system &&  eval "$(rbenv init -)"; gem install bundler' returned a non-zero code: 1

docker build --rm -t ubuntu-ruby . returned exit code 1
```